steps:
    - task: CmdLine@2
      displayName: 'Command Line Script - Comprimir artefacto'
      inputs:
        script: |
          cd "$(System.DefaultWorkingDirectory)/app"
          rm -rf node_modules
          rm -f package-lock.json
          npm install --only=prod
          zip -r -D app.zip server.js node_modules/*

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
          PathtoPublish: $(System.DefaultWorkingDirectory)/app/app.zip
          ArtifactName: Artifact

    - task: ArtifactoryGenericUpload@1
      displayName: 'Publish Artifact to Artifactory'
      inputs:
          artifactoryService: Artifactory
          fileSpec: |
              {
                "files": [
                  {
                    "pattern": "$(System.DefaultWorkingDirectory)/app/app.zip",
                    "target": "$(Artifactory.Repository)/$(Build.Repository.Name)/$(Build.BuildNumber)/"
                  }
                ]
              }
          collectBuildInfo: true